start_download:
  name: Start download
  description: Start to download with aria2
  fields:
    url:
      name: Url
      description: Url of the file to download
      required: true
      selector:
        text:
    server_entry_id:
      name: server_entry_id
      description: The server entry id
      required: true
      selector:
        text:

pause_download:
  name: Pause a download
  description: Pause a download started with aria2
  fields:
    gid:
      name: gid
      description: the gid of the download
      required: true
      selector:
        text:
    server_entry_id:
      name: server_entry_id
      description: The server entry id
      required: true
      selector:
        text:

remove_download:
  name: Remove a download
  description: Remove a download started with aria2
  fields:
    gid:
      name: gid
      description: the gid of the download
      required: true
      selector:
        text:
    server_entry_id:
      name: server_entry_id
      description: The server entry id
      required: true
      selector:
        text:

resume_download:
  name: Resume a download
  description: Resume a download started with aria2
  fields:
    gid:
      name: gid
      description: the gid of the download
      required: true
      selector:
        text:
    server_entry_id:
      name: server_entry_id
      description: The server entry id
      required: true
      selector:
        text: